-- Expected: 12 pp_* tables, InnoDB, utf8mb4_unicode_ci.
SELECT TABLE_NAME, ENGINE, TABLE_COLLATION
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'pelisenpareja' AND TABLE_NAME LIKE 'pp\_%'
ORDER BY TABLE_NAME;
SELECT COUNT(*) AS expected_12_tables FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'pelisenpareja' AND TABLE_NAME LIKE 'pp\_%';
