import { Catalog, Decision, Group, Title } from './models';
export const DEMO_PARTNER_VOTES: Record<string, Decision> = {'movie:157336':'like','tv:66732':'like','movie:238':'dislike'};
export const DEMO_CATALOG: Catalog = {
 providers: [{provider_id:8,provider_name:'Netflix',logo_path:'/pbpMk2JmcoNnQwx5JGpXngfoWtp.jpg'},{provider_id:119,provider_name:'Prime Video',logo_path:'/emthp39XA2YScoYL1p0sdbAH2WA.jpg'},{provider_id:337,provider_name:'Disney+',logo_path:'/97yvRBw1GzX7fXprcF80er19ot.jpg'},{provider_id:1899,provider_name:'HBO Max',logo_path:'/jbe4gVSfRlbPTdESXhEKpornsfu.jpg'},{provider_id:350,provider_name:'Apple TV',logo_path:'/2E03IAZsX4ZaUqM7tXlctEPMGWS.jpg'},{provider_id:63,provider_name:'Filmin',logo_path:'/kO2SWXvDCHAquaUuTJBuZkTBAuU.jpg'}],
 movie_genres:[{id:28,name:'Acción'},{id:12,name:'Aventura'},{id:16,name:'Animación'},{id:35,name:'Comedia'},{id:18,name:'Drama'},{id:27,name:'Terror'},{id:10749,name:'Romance'},{id:878,name:'Ciencia ficción'},{id:99,name:'Documental'}],tv_genres:[{id:18,name:'Drama'},{id:35,name:'Comedia'},{id:10765,name:'Ciencia ficción y fantasía'},{id:10764,name:'Reality'}],
 countries:[{iso_3166_1:'ES',native_name:'España',english_name:'Spain'},{iso_3166_1:'US',native_name:'Estados Unidos',english_name:'United States'},{iso_3166_1:'GB',native_name:'Reino Unido',english_name:'United Kingdom'},{iso_3166_1:'FR',native_name:'Francia',english_name:'France'},{iso_3166_1:'IN',native_name:'India',english_name:'India'},{iso_3166_1:'KR',native_name:'Corea del Sur',english_name:'South Korea'}]
};
export const DEMO_GROUP: Group = {id:1,name:'Nuestro sofá',owner_uid:'demo',invite_code:'SOFA2026DEMO',region:'ES',media_type:'both',providers:[8,119,337,1899],excluded_genres:[],excluded_countries:[],members:[{uid:'demo',display_name:'Tú',photo_url:''},{uid:'demo-partner',display_name:'Tu pareja',photo_url:''}],invites:[],match_count:0,filter_version:1};
export const DEMO_TITLES: Title[] = [
 {id:157336,media_type:'movie',title:'Interstellar',overview:'Un grupo de exploradores viaja más allá de nuestra galaxia para descubrir si la humanidad tiene un futuro entre las estrellas. Un viaje sobre el tiempo, el amor y todo lo que nos une.',poster_path:'/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',backdrop_path:'/xJHokMbljvjADYdit5fK5VQsXEG.jpg',date:'2014-11-05',rating:8.5,runtime:169,seasons:null,genres:[{id:878,name:'Ciencia ficción'},{id:18,name:'Drama'}],countries:['US'],providers:[DEMO_CATALOG.providers[2]!],watch_url:'https://www.themoviedb.org/movie/157336/watch'},
 {id:313369,media_type:'movie',title:'La La Land',overview:'Mia sueña con ser actriz. Sebastian quiere abrir su propio club de jazz. En Los Ángeles, sus caminos se cruzan y les recuerdan que algunos sueños se viven mejor acompañados.',poster_path:'/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',backdrop_path:'/qJeU7KM4nYm6V4dTCdXzY9qD1WJ.jpg',date:'2016-12-09',rating:7.9,runtime:128,seasons:null,genres:[{id:10749,name:'Romance'},{id:18,name:'Drama'}],countries:['US'],providers:[DEMO_CATALOG.providers[1]!],watch_url:'https://www.themoviedb.org/movie/313369/watch'},
 {id:66732,media_type:'tv',title:'Stranger Things',overview:'La desaparición de un niño lleva a un pequeño pueblo a descubrir un misterio que conecta experimentos secretos, fuerzas sobrenaturales y una niña extraordinaria.',poster_path:'/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',backdrop_path:'/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',date:'2016-07-15',rating:8.6,runtime:null,seasons:5,genres:[{id:18,name:'Drama'},{id:10765,name:'Ciencia ficción y fantasía'}],countries:['US'],providers:[DEMO_CATALOG.providers[0]!],watch_url:'https://www.themoviedb.org/tv/66732/watch'},
 {id:238,media_type:'movie',title:'El padrino',overview:'La historia de la familia Corleone, una dinastía en la que la lealtad, el poder y las decisiones de un hijo cambian para siempre el destino de todos.',poster_path:'/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',backdrop_path:'/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',date:'1972-03-14',rating:8.7,runtime:175,seasons:null,genres:[{id:18,name:'Drama'}],countries:['US'],providers:[DEMO_CATALOG.providers[1]!],watch_url:'https://www.themoviedb.org/movie/238/watch'},
 {id:900001,media_type:'tv',title:'Love Is Blind',overview:'Personas solteras se conocen y buscan una conexión antes de verse cara a cara.',poster_path:null,backdrop_path:null,date:'2020-02-13',rating:6.2,runtime:null,seasons:8,genres:[{id:10764,name:'Reality'}],countries:['US'],providers:[DEMO_CATALOG.providers[0]!],watch_url:''}
];
